build:
    environment:
        php: '7.2'
        mysql: '5.7'
        node: '8.1'
        hosts:
            laravel.dev: '127.0.0.1'
        variables:
            APP_KEY: 'base64:OYl4Bk9ekouOUIRXyeTD0FVi+cJ9D+HMyDJBgSBSUuI='
            APP_ENV: 'testing'
            APP_URL: 'http://laravel.dev'
            API_HOST: 'laravel.dev'
            DB_HOST: '127.0.0.1'
            DB_DATABASE: 'scrutinizer'
            DB_USERNAME: 'root'
            DB_PASSWORD: ''
            MAIL_DRIVER: 'log'
    cache:
        directories:
            - node_modules
            - vendor/
            - ~/.composer/cache/
    dependencies:
        before:
            - mysql -uroot -e 'CREATE DATABASE scrutinizer'
    tests:
        before:
            - chmod -R 777 storage
            - chmod -R 777 bootstrap/cache
            - npm install cross-env
            - npm install
            - npm install -g yarn
            - yarn --version
            - rm -rf node_modules && rm package-lock.json && npm cache clear --force
            - npm install
            - yarn run production
        override:
            -
                command: vendor/bin/phpunit --coverage-clover=laravel-test-examples-coverage
                coverage:
                    file: laravel-test-examples-coverage
                    format: clover
            - php-scrutinizer-run
    nodes:
        analysis:
            tests:
                override:
                    # Add the respective Scrutinizer analysis for your language like
                    #- js-scrutinizer-run
                    - php-scrutinizer-run